require('config.plugins.packer')
require('config.plugins.dap')
require('config.plugins.autopairs')
-- require('config.plugins.rosepine')
-- require('config.plugins.flash')
require('config.plugins.fugitive')
require('config.plugins.harpoon')
require('config.plugins.lsp')
require('config.plugins.luasnip')
require('config.plugins.neogit')
require('config.plugins.noice')
require('config.plugins.notify')
require('config.plugins.symbols-outline')
require('config.plugins.telescope')
require('config.plugins.treesitter')
require('config.plugins.undotree')
require('config.plugins.vimairline')
require('config.plugins.lspsaga')
